---
apiVersion: v1
kind: Service
metadata:
  name: opa
spec:
  type: ClusterIP
  ports:
    - port: 8181
      targetPort: 8181
      name: http
  selector:
    app.kubernetes.io/name: opa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: opa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opa
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: opa
          image: openpolicyagent/opa:0.60.0-static
          args:
            - "run"
            - "--server"
            - "--addr=0.0.0.0:8181"
            - "/policies/policy.rego"
          ports:
            - containerPort: 8181
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: policies
              mountPath: /policies
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health?bundle=true
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 3
            failureThreshold: 20
      volumes:
        - name: policies
          configMap:
            name: opa-policy
