---
apiVersion: v1
kind: Service
metadata:
  name: openfga
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 8081
      targetPort: 8081
      name: grpc
    - port: 3000
      targetPort: 3000
      name: playground
  selector:
    app.kubernetes.io/name: openfga
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfga
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openfga
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openfga
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done']
      containers:
        - name: openfga
          image: openfga/openfga:latest
          args:
            - "run"
          env:
            - name: OPENFGA_DATASTORE_ENGINE
              value: "postgres"
            - name: OPENFGA_DATASTORE_URI
              value: "postgres://openfga:openfga@postgres:5432/openfga?sslmode=disable"
            - name: OPENFGA_PLAYGROUND_ENABLED
              value: "true"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: grpc
            - containerPort: 3000
              name: playground
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
