---
apiVersion: v1
kind: Service
metadata:
  name: openfga
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 8081
      targetPort: 8081
      name: grpc
    - port: 3000
      targetPort: 3000
      name: playground
  selector:
    app.kubernetes.io/name: openfga
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfga
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: openfga
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openfga
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z full-postgres 5432; do echo waiting for postgres; sleep 2; done']
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      containers:
        - name: openfga
          image: openfga/openfga:v1.5.3
          args:
            - "run"
          env:
            - name: OPENFGA_DATASTORE_ENGINE
              value: "postgres"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
            # Construct URI from secret values at runtime
            - name: OPENFGA_DATASTORE_URI
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@full-postgres:5432/$(POSTGRES_DB)?sslmode=disable"
            - name: OPENFGA_PLAYGROUND_ENABLED
              value: "true"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: grpc
            - containerPort: 3000
              name: playground
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
